/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/me': RouteRecordInfo<'/albums/me', '/albums/me', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/「言葉はまるで雪の結晶。」': RouteRecordInfo<'/posts/「言葉はまるで雪の結晶。」', '/posts/「言葉はまるで雪の結晶。」', Record<never, never>, Record<never, never>>,
    '/posts/24年': RouteRecordInfo<'/posts/24年', '/posts/24年', Record<never, never>, Record<never, never>>,
    '/posts/从零开始的博客生活': RouteRecordInfo<'/posts/从零开始的博客生活', '/posts/从零开始的博客生活', Record<never, never>, Record<never, never>>,
    '/posts/从壹开始的博客生活': RouteRecordInfo<'/posts/从壹开始的博客生活', '/posts/从壹开始的博客生活', Record<never, never>, Record<never, never>>,
    '/posts/我的人生哲学': RouteRecordInfo<'/posts/我的人生哲学', '/posts/我的人生哲学', Record<never, never>, Record<never, never>>,
    '/posts/我的学习生涯': RouteRecordInfo<'/posts/我的学习生涯', '/posts/我的学习生涯', Record<never, never>, Record<never, never>>,
    '/posts/执业医师 医師免許証 Notes': RouteRecordInfo<'/posts/执业医师 医師免許証 Notes', '/posts/执业医师 医師免許証 Notes', Record<never, never>, Record<never, never>>,
    '/posts/JLPT N1 Notes': RouteRecordInfo<'/posts/JLPT N1 Notes', '/posts/JLPT N1 Notes', Record<never, never>, Record<never, never>>,
    '/posts/LIVE PROJECT': RouteRecordInfo<'/posts/LIVE PROJECT', '/posts/LIVE PROJECT', Record<never, never>, Record<never, never>>,
    '/posts/TOEFL Notes': RouteRecordInfo<'/posts/TOEFL Notes', '/posts/TOEFL Notes', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
